### ISSUE TITLE
No package matching 'monit' found available, installed or updated

### ISSUE THREAD

**Issue by Cinux90** [while-true-do/ansible-role-monit#6]
### Type of Report

Bug

### Actual behaviour

Run the role and its failed with:
```
TASK [while_true_do.monit : Set Monit to "present"] ****************************
failed: [192.168.56.102] (item=monit) => {"changed": false, "item": "monit", "msg": "No package matching 'monit' found available, installed or updated", "rc": 126, "results": ["No package matching 'monit' found available, installed or updated"]}
```

### Expected behaviour

Of course, that monit got installed :)
Looks like epel repo is needed here. So we have two options:

- Set [repo-epel](https://github.com/while-true-do/ansible-role-repo-epel) as dependency and add it into requirements.yml
- Set a hint into the README.md which inform that you need to install epel first

Whats your opinion into that issue? Lets discuses it and fix it too. :)

**Comment by daniel-schier** [comment]
Since the whole dependency thingy is buggy as hell, i think I'll go with the hint.
Thanks a lot :+1:
